/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace Voting {
      
    export type CandidateStruct = {name: string, voteCount: BigNumberish}

    export type CandidateStructOutput = [name: string, voteCount: bigint] & {name: string, voteCount: bigint }
  
    }

  export interface VotingInterface extends Interface {
    getFunction(nameOrSignature: "addCandidate" | "candidates" | "getAllVotesOfCandiates" | "getRemainingTime" | "getVotingStatus" | "owner" | "renounceOwnership" | "transferOwnership" | "vote" | "voters" | "votingEnd" | "votingStart"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'addCandidate', values: [string]): string;
encodeFunctionData(functionFragment: 'candidates', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAllVotesOfCandiates', values?: undefined): string;
encodeFunctionData(functionFragment: 'getRemainingTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'getVotingStatus', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'voters', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'votingEnd', values?: undefined): string;
encodeFunctionData(functionFragment: 'votingStart', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'addCandidate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'candidates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllVotesOfCandiates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRemainingTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVotingStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voters', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votingEnd', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votingStart', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Voting extends BaseContract {
    
    connect(runner?: ContractRunner | null): Voting;
    waitForDeployment(): Promise<this>;

    interface: VotingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addCandidate: TypedContractMethod<
      [_name: string, ],
      [void],
      'nonpayable'
    >
    

    
    candidates: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint] & {name: string, voteCount: bigint }],
      'view'
    >
    

    
    getAllVotesOfCandiates: TypedContractMethod<
      [],
      [Voting.CandidateStructOutput[]],
      'view'
    >
    

    
    getRemainingTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getVotingStatus: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    vote: TypedContractMethod<
      [_candidateIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    voters: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    votingEnd: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    votingStart: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addCandidate'): TypedContractMethod<
      [_name: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'candidates'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint] & {name: string, voteCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getAllVotesOfCandiates'): TypedContractMethod<
      [],
      [Voting.CandidateStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getRemainingTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getVotingStatus'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [_candidateIndex: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'voters'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'votingEnd'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'votingStart'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }